---@meta
---@diagnostic disable

---@class interopGlobalNodeIDInfo
---@field globalName String
---@field globalNodeIDPath String
---@field globalNodeIDHash Uint64
---@field globalNameIsAutoGenerated Bool
interopGlobalNodeIDInfo = {}

---@return interopGlobalNodeIDInfo
function interopGlobalNodeIDInfo.new() return end

---@param props table
---@return interopGlobalNodeIDInfo
function interopGlobalNodeIDInfo.new(props) return end

